name: Run tests on all maintained fyne branch

on:
  workflow_call:
    inputs:
      tags:
        description: "Tags to pass when running tests"
        required: false
        default: ""
        type: string

jobs:
  qa-develop:
    uses: fyne-io/tools/.github/workflows/fyne-qa.yml@main
    with:
      branch: develop
      tags: ${{ inputs.tags }}

  qa-latest:
    uses: fyne-io/tools/.github/workflows/fyne-qa.yml@main
    with:
      branch: master
      tags: ${{ inputs.tags }}

  qa-v2_6:
    uses: fyne-io/tools/.github/workflows/fyne-qa.yml@main
    with:
      branch: "release/v2.6.x"
      tags: ${{ inputs.tags }}
