name: Platform Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["", "stable"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "go.mod"

      - name: Tests
        run: go test -race -tags ci ./...
